### PR TITLE
Fix eslint in axisnow

### PR DESCRIPTION
**Pull request by kristojorg**
This fixes the axisnow eslint setting so that submodule continues to be linted

### CODE REVIEW

**Comment by hokei** [comment]
to get this to build I think you want to re-pull the latest axis-now-access-control-web.

**Comment by kristojorg** [comment]
Just updated the axisnow subrepo

**Comment by kristojorg** [comment]
@hokei mind giving this an approve?

**Review by hokei — APPROVED** [review]

**Comment by kristojorg** [comment]
@hokei actually I'm not sure this should be merged anymore... it updated the submodule to a different branch where I removed the typescript error, but I think the submodule has moved on from there and now this would effectively be moving it backwards? How would I know if that's the case?

**Comment by hokei** [comment]
@kristojorg ... there hasn't been changes to the submodule since the last merge though?

**Comment by kristojorg** [comment]
@hokei yea I suppose that's true... interesting. Okay well let's merge it then!

**Pull request merged**
