### PR TITLE
4.3.0

### PR DESCRIPTION
**Pull request by kristojorg**
Releases 4.3.0 to QA with the following changes:

- Documentation: update README.
- Add: Support using a library registry in the CONFIG_FILE so that the community deployment can use the SimplyE library registry to display all libraries.
- Add: Include browsing history in breadcrumbs
- Add: Add catalog button on openE home page
- Fix: Protect against invalid redirect uris caused by mismatch in hydration.
- Fix: Improve the appearance of home page book thumbnails for larger viewports
- tests: Add a Github Workflow to trigger integration tests in NYPL-Simplified/integration-tests-web.
- Fix: Improve UI in cases where server throws a 401 error

### CODE REVIEW

**Comment by kristojorg** [comment]
Oh whoops I just messed this up by merging #245 into dev... I'm going to update this and then @kaplanmichael you don't need to re-review all the code in these release PRs, I just read through the commits and mainly check the version number and changelog

**Comment by kaplanmichael** [comment]
> Oh whoops I just messed this up by merging #245 into dev... I'm going to update this and then @kaplanmichael you don't need to re-review all the code in these release PRs, I just read through the commits and mainly check the version number and changelog

OK no problem; let me know when it's ready for me to have a look.

**Comment by kristojorg** [comment]
Ok this should be good to go @kaplanmichael

**Review by kaplanmichael — APPROVED** [review]
LGTM

**Pull request merged**
