### PR TITLE
OE-716:update favicon

### PR DESCRIPTION
**Pull request by oliviawongnyc**
Adds new favicon, per [OE-716](https://jira.nypl.org/browse/OE-716).

### CODE REVIEW

**Comment by samanthaandrews** [comment]
It looks good but a little pixelated to me! Could you send the preview link to Jen to review and see what she thinks? She might want to give us a higher res version.

**Comment by oliviawongnyc** [comment]
> 

Yes! Will add a comment on the ticket.

**Comment by oliviawongnyc** [comment]
Alright, @samanthaandrews, switched out the favicons. LMK how that looks to you.

**Comment by samanthaandrews** [comment]
Looks way better. I do see a white background on it, not sure if that is what Jennifer intended.
Screen Shot 2022-11-15 at 3 08 37 PM

**Comment by oliviawongnyc** [comment]
> Looks way better. I do see a white background on it, not sure if that is what Jennifer intended. Screen Shot 2022-11-15 at 3 08 37 PM

Hmm, I'll confirm with her.

**Comment by oliviawongnyc** [comment]
@samanthaandrews – updated favicon again and it's ready for one last review!

**Review by samanthaandrews — APPROVED** [review]

**Comment by samanthaandrews** [comment]
Let's merge this today!

**Pull request merged**
