### PR TITLE
Service worker

### PR DESCRIPTION
**Pull request by kristojorg**
This PR addresses part of [SIMPLY-3180](https://jira.nypl.org/browse/SIMPLY-3180). We previously did not properly require the sw.js file from library-simplified-webpub-viewer. I have copied it manually over into our public folder for the time being... I'm not sure a better way to serve a static file from a node_module at the moment using next.js. We will want to get rid of it once we migrate to the new web-reader.

### CODE REVIEW

**Comment by kristojorg** [comment]
I also had to make a new https cert for development, because the one in the repo was expired

**Comment by kristojorg** [comment]
@kaplanmichael can I get a review on this by chance? I basically just copied the service worker file from the web reader over to this repo so we can properly serve it for now. In the future we will need to find a different pattern, but this is a working fix for now.

**Comment by kaplanmichael** [comment]
> @kaplanmichael can I get a review on this by chance? I basically just copied the service worker file from the web reader over to this repo so we can properly serve it for now. In the future we will need to find a different pattern, but this is a working fix for now.

@kristojorg I haven't been able to review this one because I am unable to read books on my local 

> @kaplanmichael can I get a review on this by chance? I basically just copied the service worker file from the web reader over to this repo so we can properly serve it for now. In the future we will need to find a different pattern, but this is a working fix for now.

@kristojorg , testing this on the Vercel preview instance using "Exile for Dreamers", the book loaded properly.  I did see this, but I am not sure if that reflects a problem of some sort?    
image

**Comment by kristojorg** [comment]
I believe that is unrelated to this PR. Hopefully all those weird errors will be gone with the new web reader

**Comment by kaplanmichael** [comment]
> I believe that is unrelated to this PR. Hopefully all those weird errors will be gone with the new web reader

Ah OK cool.  It said "Service Worker" in the error's URL so I wanted to be sure.

**Review by kaplanmichael — APPROVED** [review]
Good to go.

**Pull request merged**
