### PR TITLE
SFR-1242: Install missing dependencies

### PR DESCRIPTION
**Pull request by samanthaandrews**
- Some of the dependencies listed in the `fetch-config.js` and `dev-server.js` files were not installed as dependencies in the project. This PR adds `fs`, `path`, `tslib`, `https`, `url`, and `yaml` to `package.json`.

[https://jira.nypl.org/browse/SFR-1242](https://jira.nypl.org/browse/SFR-1242)

This is failing the Storybook check, but @hokei and I chatted and decided to create another ticket to fix the Storybook build. FWIW, Storybook builds also fail on `dev` branch.

### CODE REVIEW

**Comment by hokei** [comment]
FYI for the future:  If you use the `no-changelog` label it will skip the changelog check (I've only managed to get it working reliably if you do it before you start the PR, though)

**Comment by samanthaandrews** [comment]
> FYI for the future: If you use the `no-changelog` label it will skip the changelog check (I've only managed to get it working reliably if you do it before you start the PR, though)

Ah, good to know, thanks!

**Review by kristojorg — APPROVED** [review]
Looks great to me, thanks!

**Comment by kristojorg** [comment]
I will go ahead and merge even with the failing storybook build, and we will fix that later.

**Pull request merged**
