### PR TITLE
Hotfix use Chakra footer as footer everywhere

### PR DESCRIPTION
**Pull request by samanthaandrews**
Use the chakra footer from the homepage in the web app too

### CODE REVIEW

**Review by Toxiapo — APPROVED** [review]
Nice! So we can use Chakra components even if the file is using `/** @jsxImportSource theme-ui */`

**Review by Toxiapo — CHANGES_REQUESTED** [review]
Could you also remove the old component and update the test?

**Comment by samanthaandrews** [comment]
@Toxiapo Good catch. I made those updates!

**Review by Toxiapo — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
